### PR TITLE
Whoops, not setting issuer correctly.

### PR DESCRIPTION
**Pull request by RackerWilliams**

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
Looks like you hard coded it in? This matches the behavior we were expecting, but i thought you said you were going to make it an optional argument into the method?

**Comment by RackerWilliams** [comment]
See line 23, it is not a constant.  It is a parameter into the transform with a default value.   The scala bit doesn't set the param so the default is used.  Wanted to get the fix out quickly.  I'll modify the scala bit but wanted to unblock.

**Comment by adrianjgeorge** [comment]
kk. Is that what you want the default behavior to be or is the old behavior the default? I can see an argument for either.

**Comment by RackerWilliams** [comment]
I like the idea of being a parameter with a defualt value -- rather than copying the value.  Cus when you copy -- you are essentially lying.

**Comment by adrianjgeorge** [comment]
That makes sense to me, the other guy didn't issue that assertion so we shouldn't put their name on it. Do you want the default to be so repose specific or would something more neutral make more sense? I guess part of the question is what's the timeline on the being able to pass in a value?

**Comment by RackerWilliams** [comment]
I'm okay with it being repose for now.  I don't mind changing it either.  Need to know your timelines.  In meetings until 3:30 today...so can't work on scala interface changes until then. :-)

**Comment by adrianjgeorge** [comment]
we'll leave it repose for now

**Pull request merged**
