### PR TITLE
Added Scalastyle support to the entire project.

### PR DESCRIPTION
**Pull request by wdschei**
I also fixed the one Scalastyle finding so that it would pass.

### CODE REVIEW

**Comment by RackerWilliams** [comment]
So the only styles we agree on are spaces?

**Comment by wdschei** [comment]
There was only a single space needed to make it pass the Scalastyle config used in the current Repose build.

**Comment by RackerWilliams** [comment]
...but my point is if you look at the configuration file, whitespace issues are the only ones you are looking at, and that seems strange.

**Comment by wdschei** [comment]
That is what Repose is currently using. If we want to go a little more strict, then we can start with the default config and then back it down a little. The default is here, but is VERY strict.

- https://github.com/scalastyle/scalastyle/blob/master/src/main/resources/default_config.xml

**Comment by wdschei** [comment]
Using the default generates the following:

```<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0">
 <file name="./core/src/main/scala/com/rackspace/identity/components/AttributeMapper.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error column="39" line="225" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="36" line="226" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="39" line="277" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="28" line="278" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="24" line="283" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="18" line="143" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="18" line="148" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="8" line="226" source="org.scalastyle.scalariform.IfBraceChecker" severity="warning" message="If block needs braces"/>
  <error column="8" line="120" source="org.scalastyle.scalariform.ForBraceChecker" severity="warning" message="Use braces in for comprehensions"/>
  <error column="8" line="129" source="org.scalastyle.scalariform.ForBraceChecker" severity="warning" message="Use braces in for comprehensions"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
  <error column="6" line="57" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="6" line="58" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="6" line="59" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="19" line="74" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="19" line="75" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="8" line="157" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="8" line="160" source="org.scalastyle.scalariform.TodoCommentChecker" severity="warning" message="Use of TODO/FIXME comment"/>
 </file>
 <file name="./core/src/test/scala/com/rackspace/identity/components/AttributeMapperSuite.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error line="65" source="org.scalastyle.file.FileLineLengthChecker" severity="warning" message="File line length exceeds 160 characters"/>
  <error column="57" line="105" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="24" line="121" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="6" line="45" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="46" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="47" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="4" line="96" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="4" line="104" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
 </file>
 <file name="./cli/nailgun-server/src/main/scala/com/rackspace/identity/components/cli/NailgunServer.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error column="33" line="123" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="27" line="134" source="org.scalastyle.scalariform.NullChecker" severity="warning" message="Avoid using null"/>
  <error column="19" line="90" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="48" line="104" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="55" line="106" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="21" line="146" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="19" line="153" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="17" line="156" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="170" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
  <error column="6" line="52" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="6" line="53" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="6" line="54" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
  <error column="6" line="55" source="org.scalastyle.scalariform.FieldNamesChecker" severity="warning" message="Field name does not match the regular expression '^[a-z][A-Za-z]*$'"/>
 </file>
 <file name="./cli/attribmap2xsl/src/main/scala/com/rackspace/identity/components/cli/AttribMap2XSL.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error column="12" line="85" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="41" line="93" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="49" line="95" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="43" source="org.scalastyle.scalariform.MethodLengthChecker" severity="warning" message="Method is longer than 50 lines"/>
  <error column="6" line="107" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="6" line="120" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
 </file>
 <file name="./cli/attribmap/src/main/scala/com/rackspace/identity/components/cli/AttribMap.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error column="12" line="93" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="41" line="101" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="49" line="103" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="43" source="org.scalastyle.scalariform.MethodLengthChecker" severity="warning" message="Method is longer than 50 lines"/>
  <error column="6" line="115" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="6" line="128" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
 </file>
 <file name="./cli/attribmap2json/src/main/scala/com/rackspace/identity/components/cli/AttribMap2JSON.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error column="12" line="85" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="41" line="92" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="49" line="94" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="43" source="org.scalastyle.scalariform.MethodLengthChecker" severity="warning" message="Method is longer than 50 lines"/>
  <error column="6" line="106" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="6" line="118" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
 </file>
 <file name="./cli/attribmap2xml/src/main/scala/com/rackspace/identity/components/cli/AttribMap2XML.scala">
  <error line="1" source="org.scalastyle.file.HeaderMatchesChecker" severity="warning" message="Header does not match expected text"/>
  <error column="12" line="84" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="41" line="91" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="49" line="93" source="org.scalastyle.file.RegexChecker" severity="warning" message="Regular expression matched 'println'"/>
  <error column="6" line="42" source="org.scalastyle.scalariform.MethodLengthChecker" severity="warning" message="Method is longer than 50 lines"/>
  <error column="6" line="105" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="6" line="117" source="org.scalastyle.scalariform.PublicMethodsHaveTypeChecker" severity="warning" message="Public method must have explicit type"/>
  <error column="0" line="1" source="org.scalastyle.scalariform.SpaceAfterCommentStartChecker" severity="warning" message="Insert a space after the start of the comment"/>
 </file>
</checkstyle>```

All of them are `WARNING`'s, but we can disable the rules we don't care about.

**Comment by RackerWilliams** [comment]
Hey, I've changed my mind.  Go ahead and add the default_config to all code.  I'll make the required changes.  BTW, there is a way to have scalastyle skip a line:

You can actually switch things off at a particular line number using comments such as 

````scala
 naughty()  // scalastyle:ignore
````

**Comment by wdschei** [comment]
I updated the location of the `scalastyle_config.xml` to the new `project` directory so that IntelliJ IDEA will automatically apply the rules in the IDE. I also updated the `scalastyle_config.xml` to base it on the default v0.8.0 release with a couple of minor tweaks and the whitespace additions from the Repose project.

The only remaining failures are the `TODO` in `AttributeMapper` as well as an `if`/`else` block that flags for not using curly braces. I didn't fix this block as I didn't know if you wanted to leave it and use a comment to switch off that finding.

**Comment by RackerWilliams** [comment]
I suppose one of the tweaks was the 50 line method limit,  cus I don't see that being addressed.

re:Header check.  New files will have 2017 in them right?  So is this going to force all files to have to change the date every year?

Do you mind going ahead and fixing the remaining two items?  I'm okay with the if/else having curlies and you can remove the TODO from the comments.

**Comment by wdschei** [comment]
I originally just increased the `MethodLengthChecker`'s `maxLength` from 50 to 100. Since that just served to put a band-aid on the actual issue, I have reverted that back to the default and used the ignore comment to prevent the finding.

Along that same line of thought, I have also reverted the `scalastyle_config.xml` back to the default and only made minimal modifications beyond the whitespace check additions. All findings were checked for desirability and either fixed or explicitly ignored with a comment.

The only rule that was entirely disabled was the `NullChecker` as this eases the interaction with the legacy Java API's. The only other modification was to the `FieldNamesChecker` and that was to expand it to allow numbers in a name as well as Java style constants.

**Comment by RackerWilliams** [comment]
I can live with all of that.  What about my question regarding the HeaderCheck above?

**Comment by wdschei** [comment]
If the `HeaderMatchesChecker` is not disabled, then it would generate a finding because I don't think there is a way to make that check use a REGEX.

**Comment by RackerWilliams** [comment]
Okay, looks good.

**Pull request merged**
