### PR TITLE
Added tests for mapping:get-attribute and mapping:get-attributes calls.

### PR DESCRIPTION
**Pull request by RackerWilliams**

### CODE REVIEW

**Comment by dmnjohns** [comment]
Actually, I'm surprised these passed. I think policy validation gets run by the `AttributeMapperSuite` tests, in which case, I would have expected the XPath parser to throw an exception when it encountered the `get-attribute` function, which has not been declared.

Hm...

**Comment by RackerWilliams** [comment]
You're right these should not have passed -- at all.   Try going back to your original test suite.  Misspell get-attributes -- or pass the wrong number of params.  Does it catch it there but not here?

**Comment by dmnjohns** [comment]
So yes, in my original test suite, using `get-attributes` works (as expected), but using `get-attribute` yields the following:

```
Tests in error:
  A Valid Policy Validates (src\/test\/resources\/tests\/validate-policy-tests\/valid\/simple-remote.xml validated with xerces)(com.rackspace.identity.components.ValidatePolicySuite): Cannot find a matching 1-argument function named {http://docs.rackspace.com/identity/api/ext/MappingRules}get-attribute()
```

**Comment by dmnjohns** [comment]
Ah. Checking the Jenkins log, it appears that my new tests were not run. Which implies that my changes were not present for the test run. That is odd, because I would have expected the merged branch to be used by the tests, but I'm guessing it's just running the tests against your branch.

**Comment by RackerWilliams** [comment]
That is weird.  Let me fix that.

**Comment by dmnjohns** [comment]
There we go, failing tests. I assume you don't want to merge these yet. Would you rather I base my changes branch off of this branch, or just merge this branch after the changes branch gets merged?

**Comment by RackerWilliams** [comment]
Go ahead and merge this.  The reality is that there's a bug in master as it is :-) . Then you can rebase and put a PR that fixes this.

**Comment by dmnjohns** [comment]
Fair enough.

**Pull request merged**
